const state={zIndex:500,calculator:{value:'0',stored:null,operator:null,reset:false},files:{Home:[['folder','Projects'],['folder','Websites'],['image','wallpaper.jpg'],['file-code','index.html'],['file-lines','notes.txt'],['file','README.md']],Desktop:[['folder','windows11 clone'],['file-code','index.html'],['file','shortcut.lnk']],Downloads:[['file-zipper','starter-pack.zip'],['file-pdf','guide.pdf']],Documents:[['file-lines','notes.txt'],['file-word','resume.docx']],Pictures:[['image','wallpaper.jpg'],['image','windows11.jpg']]}};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const startMenu=$('#startMenu'),quickPanel=$('#quickPanel'),contextMenu=$('#contextMenu'),toast=$('#toast');
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
function bringToFront(win){state.zIndex+=1;win.style.zIndex=state.zIndex;$$('.window').forEach(item=>item.classList.remove('focused'));win.classList.add('focused')}
function openWindow(id){const win=document.getElementById(id);if(!win)return;win.classList.add('visible');bringToFront(win);$$(`[data-open="${id}"]`).forEach(button=>button.classList.add('running'));startMenu.classList.remove('open');quickPanel.classList.remove('open');if(id==='explorer-window')renderFiles('Home');if(id==='notepad-window')$('#notepadText').focus()}
function closeWindow(win){win.classList.remove('visible');win.classList.remove('maximized');$$(`[data-open="${win.id}"]`).forEach(button=>button.classList.remove('running'))}
function togglePopup(popup){const wasOpen=popup.classList.contains('open');startMenu.classList.remove('open');quickPanel.classList.remove('open');if(!wasOpen)popup.classList.add('open')}
function updateClock(){const now=new Date();$('#clock').textContent=now.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});$('#date').textContent=now.toLocaleDateString([], {month:'2-digit',day:'2-digit',year:'numeric'})}setInterval(updateClock,1000);updateClock();
function renderFiles(location){const files=state.files[location]||state.files.Home;$('#explorerPath').textContent=location;$('#explorerHeading').textContent=location;$('#fileGrid').innerHTML=files.map(([icon,name])=>`<button class="file-card" data-file="${name}"><i class="fa-solid fa-${icon} ${icon==='folder'?'explorer-color':'notepad-color'}"></i><span>${name}</span></button>`).join('');$$('.sidebar-item').forEach(button=>button.classList.toggle('active',button.dataset.location===location));$$('.file-card').forEach(card=>card.addEventListener('dblclick',()=>showToast(`${card.dataset.file} opened`)))}
function filterApps(){const query=$('#startSearch').value.toLowerCase();$$('#pinnedGrid button').forEach(app=>{app.hidden=!app.textContent.toLowerCase().includes(query)})}
function calculate(type,button){const calc=state.calculator;const display=$('#calculatorDisplay');if(type==='number'){if(calc.reset||calc.value==='0')calc.value=button.textContent;else calc.value+=button.textContent;calc.reset=false}if(type==='decimal'&&!calc.value.includes('.'))calc.value+='.';if(type==='clear'){calc.value='0';calc.stored=null;calc.operator=null}if(type==='operator'){if(button.textContent==='+/-')calc.value=String(Number(calc.value)*-1);else if(button.textContent==='%')calc.value=String(Number(calc.value)/100);else{calc.stored=Number(calc.value);calc.operator=button.textContent;calc.reset=true}}if(type==='equals'&&calc.operator){const current=Number(calc.value);const operators={'+':(a,b)=>a+b,'−':(a,b)=>a-b,'×':(a,b)=>a*b,'÷':(a,b)=>b===0?0:a/b};calc.value=String(operators[calc.operator](calc.stored,current));calc.operator=null;calc.reset=true}display.textContent=calc.value}
$$('[data-calc]').forEach(button=>button.addEventListener('click',()=>calculate(button.dataset.calc,button)));
function makeDraggable(header){header.addEventListener('pointerdown',event=>{const win=header.closest('.window');if(win.classList.contains('maximized')||event.target.closest('.window-controls'))return;bringToFront(win);const startX=event.clientX,startY=event.clientY,left=win.offsetLeft,top=win.offsetTop;const move=moveEvent=>{win.style.left=`${left+moveEvent.clientX-startX}px`;win.style.top=`${top+moveEvent.clientY-startY}px`};const stop=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',stop)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',stop)})}
$$('[data-open]').forEach(button=>button.addEventListener('click',()=>openWindow(button.dataset.open)));$('#startButton')?.addEventListener('click',event=>{event.stopPropagation();togglePopup(startMenu)});$('#taskbarSearch')?.addEventListener('click',()=>{startMenu.classList.add('open');quickPanel.classList.remove('open');$('#startSearch')?.focus()});$('#systemTray')?.addEventListener('click',event=>{event.stopPropagation();togglePopup(quickPanel)});$('#startSearch')?.addEventListener('input',filterApps);$('#allAppsBtn')?.addEventListener('click',()=>startMenu.classList.add('all-apps'));$('#backToPinned')?.addEventListener('click',()=>startMenu.classList.remove('all-apps'));$('#moreRecommended')?.addEventListener('click',()=>showToast('You are viewing recent items'));$('#powerButton')?.addEventListener('click',()=>showToast('Power options are simulated in this clone'));$('#recycleBin')?.addEventListener('dblclick',()=>showToast('Recycle Bin is empty'));
$$('.window').forEach(win=>{win.addEventListener('pointerdown',()=>bringToFront(win));makeDraggable($('.window-header',win));win.querySelectorAll('[data-window-action]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.windowAction;if(action==='close')closeWindow(win);if(action==='minimize')win.classList.remove('visible');if(action==='maximize')win.classList.toggle('maximized')}))});
$$('.sidebar-item').forEach(button=>button.addEventListener('click',()=>renderFiles(button.dataset.location)));$$('.quick-tile').forEach(tile=>tile.addEventListener('click',()=>{tile.classList.toggle('active');$('#panelStatus').textContent=`${tile.dataset.quick} ${tile.classList.contains('active')?'on':'off'}`}));$('#panelSettings').addEventListener('click',()=>openWindow('settings-window'));
const notepad=$('#notepadText');notepad.value=localStorage.getItem('windows11-clone-note')||'';notepad.addEventListener('input',()=>{localStorage.setItem('windows11-clone-note',notepad.value);$('#saveStatus').textContent='Saved locally'});
$('.address-form').addEventListener('submit',event=>{event.preventDefault();const value=$('#addressInput').value.trim();$('#browserPage').innerHTML=`<div class="edge-mark"><i class="fa-brands fa-edge"></i></div><h2>${value?`Results for “${value.replace(/</g,'&lt;')}”`:'Search the web'}</h2><p>This offline browser preview cannot navigate the live web.</p>`;showToast('Offline preview loaded')});
document.addEventListener('contextmenu',event=>{if(event.target.closest('.window,.taskbar,.start-menu,.quick-panel'))return;event.preventDefault();contextMenu.style.left=`${Math.min(event.clientX,window.innerWidth-220)}px`;contextMenu.style.top=`${Math.min(event.clientY,window.innerHeight-170)}px`;contextMenu.classList.add('open')});$$('[data-context]').forEach(item=>item.addEventListener('click',()=>{contextMenu.classList.remove('open');if(item.dataset.context==='refresh')showToast('Desktop refreshed');if(item.dataset.context==='personalize')openWindow('settings-window');if(item.dataset.context==='settings')openWindow('settings-window')}));document.addEventListener('click',event=>{if(!event.target.closest('#startMenu,#startButton,#taskbarSearch'))startMenu.classList.remove('open');if(!event.target.closest('#quickPanel,#systemTray'))quickPanel.classList.remove('open');if(!event.target.closest('#contextMenu'))contextMenu.classList.remove('open')});document.addEventListener('keydown',event=>{if(event.key==='Escape'){startMenu.classList.remove('open');quickPanel.classList.remove('open');contextMenu.classList.remove('open')}if(event.key==='Enter'&&document.activeElement===notepad)showToast('Note saved locally')});renderFiles('Home');